python runComparisonCortes.py 'HMuTau'
python runComparisonCortes.py 'HMuMu'
python runComparisonCortes.py 'HTauTau'
python runComparisonCortes.py 'TT2L2Nu'
python runComparisonCortes.py 'ZLL'

python plotMany.py  'MM_MuonLead'
python plotMany.py  'MM_MuonSubLead'        
python plotMany.py  'MM_METEt'      
python plotMany.py  'MM_deltaPhiMu1Met'     
python plotMany.py  'MM_deltaPhiMu2Met'     
python plotMany.py  'MM_deltaPhiMu1Mu2'     
python plotMany.py  'MM_deltaEtaMu1Mu2'     
python plotMany.py  'ME_MuonLead'   
python plotMany.py  'ME_ElectronLead'       
python plotMany.py  'ME_METEt'      
python plotMany.py  'ME_deltaPhiMuMet'      
python plotMany.py  'ME_deltaPhiEleMet'     
python plotMany.py  'ME_deltaPhiMuEle'      
python plotMany.py  'ME_deltaEtaMuEle'      
python plotMany.py 'InvariantMassDiMuon'
python plotMany.py 'InvariantMassMuonElectron'
python plotMany.py 'CollinearMassDiMuon'
python plotMany.py 'CollinearMassMuonElectron'

